### PR TITLE
Date fix to make default dates fit STAC json schema

### LINKED ISSUE #21: Wrench fails to write required key datetime if it cannot be determined from the file.
https://github.com/PDAL/wrench/blob/main/src/vpc.cpp#L371-L372

In the creation of a VPC, which is at its core a STAC ItemCollection, Wrench fails to write the required key `datetime` if the date cannot be parsed

I think either an exception should be thrown, or a default datetime should be written to the VPC.

STAC Item Schema for reference: https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json

### PR DESCRIPTION
**Pull request by kylemann16**
Fixes #21. Change default dates to fit STAC JSON schema. Add warnings to let users know the input data has out of range dates.

STAC Item json schema for reference: https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json

### CODE REVIEW

File: src/vpc.cpp [hunk 1]
```diff
@@ -368,8 +368,18 @@ std::string dateTimeStringFromYearAndDay(int year, int dayOfYear)
 {
     bool leapYear = isLeapYear(year);
 
-    if (year < 0) return "";  // Year is negative
-    if ((dayOfYear < 1) || (dayOfYear > (leapYear ? 366 : 365))) return ""; // Day of year is out of range
+    if (year < 0)  // Year is negative
+    {
+        std::cout << "Warning: year(" << year <<
```
Comment (hobu) [inline src/vpc.cpp:373]: should this be to cerr?

Comment (kylemann16) [reply src/vpc.cpp:373]: Yeah probably, will change.

**Review by wonder-sk — APPROVED** [review]

**Comment by wonder-sk** [comment]
Thanks @kylemann16!
